### ISSUE TITLE
event_project_followers permission error

### ISSUE THREAD

**Issue by acysos** [avanzosc/event-wip#90]
Hello,

I have detected a permission error. When launch the mail.followers create.

File event_event.py line 32:

``` python
follower_obj.create({'res_model': 'event.event',
                     'res_id': event.id,
                     'partner_id': partner.id})
```

It need permission over mail.followers that only the group Administration/Settings have it. I think that the better solution is Superuser, so the user haven't permission over mail.followers:

``` python
follower_obj.sudo().create({'res_model': 'event.event',
                            'res_id': event.id,
                            'partner_id': partner.id})
```

Greetings,
Ignacio

**Comment by oihane** [comment]
We have done some changes in that module and it does not contain what you say. Can you check it out again with latest code, the module you are testing is in avanzosc/odoo-addons repo, not in here.

Thanks for checking out our modules.

**Comment by oihane** [comment]
This error should not happen anymore so I'll close this issue
